In [1]:
import gymnasium as gym
env = gym.make("CartPole-v1", render_mode="rgb_array")

In [2]:
obs = env.reset()
obs

(array([ 0.02348993, -0.01645448,  0.02124353,  0.00787967], dtype=float32),
 {})

In [3]:
env.render()

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [4]:
env.action_space

Discrete(2)

In [5]:
action = 1
obs, reward, done, trun, info = env.step(action)
obs

array([ 0.02316084,  0.17835647,  0.02140113, -0.2780257 ], dtype=float32)

In [6]:
reward

1.0

In [7]:
done

False

In [8]:
info

{}

In [9]:
totals = []    
for episode in range(500):
    episode_rewards = 0
    obs = env.reset()
    for step in range(1000):
        action = env.action_space.sample()
        obs, reward, done, trun, info = env.step(action)
        episode_rewards += reward
        if done:
            break
    totals.append(episode_rewards)

In [10]:
import numpy as np

np.mean(totals), np.std(totals), np.min(totals), np.max(totals)

(21.496, 10.964031375365542, 8.0, 74.0)

In [11]:
# Build a Neural Network policy with Tensorflow

import tensorflow as tf
from tf.contrib.layers import fully_connected

# specify the neural net architecture
n_inputs = 4
n_hidden = 4
n_outputs = 1
initializer = tf.contrib.layers.variance.scaling_initializer()

#  Build the neural net
X = tf.placeholder(tf.float32, shape=[None, n_inputs])
hidden = fully_connected(X, n_hidden, activation_fn=tf.nn.elu,
                        weights_initializer=initializer)
logits = fully_connected(hidden, n_outputs, activation_fn=None,
                        weights_initializer=initializer)
outputs = tf.nn.sigmoid(logits)

# Select a random action based on the estimated probabilities
p_left_and_right = tf.concat(axis=1, values=[outputs, 1-outputs])
action = tf.multinomial(tf.log(p_left_and_right), num_samples=1)

init = tf.global_variables_initializer()


: 